# Generated by Django 3.2 on 2021-06-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20210619_0955'),
        ('administrator', '0009_auto_20210618_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstscores', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('secondscores', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('thirdscores', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('totalca', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('examscore', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grandtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.session')),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.subject')),
                ('subjectteacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.subjectteacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.term')),
            ],
        ),
    ]
