# Generated by Django 3.2 on 2021-06-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210619_0955'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='grandtotal',
            new_name='subjaverage',
        ),
        migrations.AddField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scores',
            name='subjectposition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='subjecttotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
