# Generated by Django 3.2 on 2021-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210620_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='highest_inclass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='lowest_inclass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='subjectgrade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='subjectrating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
