# Generated by Django 3.2 on 2021-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_affective_psychomotor_rating_studentaffective_studentpsychomotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
