# Generated by Django 3.2 on 2021-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20210822_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='highest_inclass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='lowest_inclass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
