# Generated by Django 3.2 on 2021-08-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20210822_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpsychomotor',
            old_name='pyschomotor',
            new_name='psychomotor',
        ),
    ]
