# Generated by Django 3.2 on 2021-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_result_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='owing_status',
            field=models.CharField(blank=True, default='open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(blank=True, default='yes', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='attendance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
