# Generated by Django 3.2 on 2021-09-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_reg_no'),
        ('teacher', '0018_admissionnumber_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_prefix', models.CharField(default='No', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
            ],
        ),
    ]
