# Generated by Django 3.2 on 2021-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_regprefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regprefix',
            name='reg_prefix',
            field=models.CharField(max_length=20),
        ),
    ]
