# Generated by Django 3.2 on 2021-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_scores_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualresult',
            name='annualaverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='annualtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
