# Generated by Django 3.2 on 2021-06-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_city_lga'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.country'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.city'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.country'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.lga'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.state'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.city'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.lga'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.state'),
        ),
    ]
