# Generated by Django 3.2 on 2021-06-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_city_lga'),
        ('accounts', '0002_auto_20210604_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.city'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.country'),
        ),
        migrations.AddField(
            model_name='client',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.lga'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.state'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
