# Generated by Django 3.2 on 2021-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210606_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
    ]
