# Generated by Django 3.2 on 2021-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210519_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='school_type',
        ),
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
