# Generated by Django 3.2 on 2021-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210606_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
