# Generated by Django 3.2 on 2021-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_lga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='academic_qualification',
            new_name='discipline',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.CharField(blank=True, choices=[('SSCE', 'SSCE'), ('NCE', 'NCE'), ('OND', 'OND'), ('HND', 'HND'), ('BSC', 'BSC'), ('B.ED', 'B.ED'), ('MA', 'MA'), ('MSC', 'MSC'), ('PHD', 'PHD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='othername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
