# Generated by Django 3.2 on 2021-06-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20210618_1650'),
        ('accounts', '0008_auto_20210613_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_admitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.studentclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_admitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='term_admitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.term'),
        ),
    ]
