# Generated by Django 3.2 on 2021-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210619_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_reg_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(default='1'),
        ),
    ]
