# Generated by Django 3.2 on 2021-09-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210904_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='default_img.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='default_img.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default='default_img.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
