# Generated by Django 3.2 on 2021-10-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211023_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='firstname',
        ),
    ]
