# Generated by Django 3.2 on 2021-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211025_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=20),
        ),
    ]
