# Generated by Django 3.2 on 2021-12-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_teacher_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentfirstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parentsurname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
