# Generated by Django 3.2 on 2021-12-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211203_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parentfirstname',
            new_name='p_firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parentsurname',
            new_name='p_surname',
        ),
    ]
