# Generated by Django 3.2 on 2021-06-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_country_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.state')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.country')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.state')),
            ],
        ),
    ]
