# Generated by Django 3.2 on 2021-05-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_date_created'),
        ('administrator', '0003_studentclass_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_open', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_closed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.term')),
            ],
        ),
    ]
