# Generated by Django 3.2 on 2021-06-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_city_lga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
