# Generated by Django 3.2 on 2021-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20210529_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
