# Generated by Django 3.2 on 2021-05-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210529_1955'),
        ('administrator', '0006_auto_20210529_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_begins', models.DateTimeField(auto_now_add=True, null=True)),
                ('term_ends', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.term')),
            ],
        ),
    ]
