# Generated by Django 3.2 on 2021-06-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classteacher',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.term'),
            preserve_default=False,
        ),
    ]
