# Generated by Django 3.2 on 2021-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20210618_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
