# Generated by Django 3.2 on 2021-08-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_classteacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacher',
            name='name',
        ),
    ]
