# Generated by Django 3.2 on 2021-08-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20210822_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectteacher',
            name='term',
        ),
    ]
