# Generated by Django 3.2 on 2021-08-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_remove_subjectteacher_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
