# Generated by Django 3.2 on 2021-10-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0018_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
