# Generated by Django 3.2 on 2021-10-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_auto_20211023_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='created_by',
            new_name='createdby',
        ),
    ]
