# Generated by Django 3.2 on 2021-12-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_guardian_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='sex',
        ),
    ]
