from django.urls import path
from . import views


urlpatterns = [
  path('setting', views.createClient, name='admin-setting'),
  path('update-profile/<str:pk>', views.updateClient, name='update-profile'),
  path('add-term', views.addTerm, name='create-term'),
  path('update-term/<str:pk>', views.editTerm, name='update-term'),
  path('profile', views.profile, name='admin-profile'),
  path('session', views.addSession, name='add-session'),
  path('all-sessions', views.allSessions, name='all-sessions'),
  path('update-session/<str:pk>', views.updateSession, name='update-session'),
  path('class', views.addClass, name='add-class'),
  path('update-class/<str:pk>', views.updateClass, name='update-class'),
  path('all-classes', views.allClasses, name='all-classes'),
  path('subject', views.addSubject, name='add-subject'),
  path('update-subject/<str:pk>', views.updateSubject, name='update-subject'),
  path('all-subjects', views.allSubjects, name='all-subjects'),
  path('attendance-setting', views.attendance_settings, name='attendance-setting'),
  path('resumption-setting', views.resumption_settings, name='resumption-setting'),
  path('resumption-dates', views.resumptionDates, name='resumption-dates'),
  path('update-resumption/<str:pk>', views.updateResumption, name='update-resumption'),
  path('subject-perclass', views.subjectPerClass, name='subject-perclass'),
  path('subject-perclass-list', views.listSubjectPerClass, name='subject-perclass-list'),
  path('subject-perclass-list/<str:pk>', views.updateSubjectPerClass, name='update-subject-perclass-list'),
  path('new-student', views.newStudent, name='new-student'),
  path('update-student/<str:pk>', views.updateStudentProfile, name='update-student'),
  path('view-student/<str:pk>', views.viewStudent, name='view-student'),
  path('list-students', views.listStudents, name='list-students'),
  # path('country-json', views.get_json_country_data, name='country-json'),
  path('state-json/<str:pk>', views.get_json_state_data, name='state-json'),
  path('lg-json/<str:pk>', views.get_json_lg_data, name='lg-json'),

  path('new-teacher', views.newTeacher, name='new-teacher'),
  path('update-teacher/<str:pk>', views.updateTeacherProfile, name='update-teacher'),
  path('view-teacher/<str:pk>', views.viewTeacher, name='view-teacher'),
  path('list-teacher', views.listTeacher, name='list-teacher'),
  path('assign-subject', views.assignSubject, name='assign-subject'),
  path('update-subject-teacher/<str:pk>', views.updateSubjectTeacher, name='update-subject-teacher'),

  path('list-subject-teachers', views.listSubjectTeachers, name='list-subject-teachers'),
  path('assign-class-teacher', views.assignClassTeacher, name='assign-class-teacher'),
  path('list-class-teacher', views.listClassTeacher, name='list-class-teacher'),
  path('update-class-teacher/<str:pk>', views.updateClassTeacher, name='update-class-teacher'),
  path('admission-list', views.admissionList, name='admission-list'),
]
